---
# An Ansible Playbook to backup the Mikrotik device's configuration to file
# Version 2 - 31/12/2010

# By Vojtech Jurcik
# Many thanks to Wynand Booysen (wynandbooysen)
################
### RouterOS ###
################

- name: Mikrotik Update
  hosts: routers
  serial: 1
  connection: network_cli 
  user: admin
  gather_facts: no
  tasks:
  - name: Check for package updates
    routeros_command:
      commands: system package update check-for-updates
  - name: Run package updates and reboot if needed
    routeros_command:
      commands: system package update install 
