---
# An Ansible Playbook to backup the Mikrotik device's configuration to file
# Version 2 - 31/12/2010

# By Vojtech Jurcik
# Many thanks to Wynand Booysen (wynandbooysen)
################
### RouterOS ###
################
- name: Mikrotik RouterOS Update
  hosts: router
  connection: network_cli
  gather_facts: true
  tasks:
   - name: Check if updates required
     routeros_command: 
       commands: system package update check-for-updates
     register: updatecheck

   - name: Run package updates and reboot if needed
     when: updatecheck is search("System is already up to date") == -1  
     routeros_command: 
        commands: system package update download
     register: download
     until: download.stdout.find('please reboot router') > -1
     retries: 3
     delay: 60

   - name: Reboot the Router if the download is successful                    
     when: (updatecheck is search("System is already up to date") == -1) and (download is search("'please reboot router") > -1)
     routeros_command: 
       commands: system reboot
     register: reboot
     async: 0
     poll: 0
